In [4]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from quack.quantifiers import CC
from quack.ensembles import EoQ
X, y = make_classification(n_samples=1000, n_classes=2, random_state=0)
ensemble = EoQ(CC(LogisticRegression(max_iter=1000)), n_estimators=30,
               selection_policy="average", random_state=0)
ensemble.fit(X, y)
X_test, y_test = make_classification(n_samples=200, n_classes=2, random_state=7)
prevalences = ensemble.predict(X_test)

In [5]:
prevalences

array([0.50166667, 0.49833333])

In [6]:
import numpy as np
_, counts = np.unique(y_test, return_counts=True)
counts / y_test.shape[0]

array([0.5, 0.5])

In [2]:
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from quack.quantifiers import CC, ACC, PCC
from quack.ensembles import FMCMQ
X, y = make_classification(n_samples=1000, n_classes=2, random_state=42)
ensemble = FMCMQ(
   classifiers=[RandomForestClassifier(), HistGradientBoostingClassifier(), LogisticRegression()],
   quantifiers=[CC(LogisticRegression(max_iter=1000)),
                ACC(LogisticRegression(max_iter=1000)),
                PCC(LogisticRegression(max_iter=1000))],
   fusion="median", random_state=0,
 )
ensemble.fit(X, y)
X_test, y_test = make_classification(n_samples=200, n_classes=2, random_state=43)
prevalences = ensemble.predict(X_test)

In [3]:
prevalences

array([0.385, 0.615])

In [4]:
import numpy as np
_, counts = np.unique(y_test, return_counts=True)
counts / y_test.shape[0]

array([0.505, 0.495])

In [1]:
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from quack.quantifiers import ACC
from quack.ensembles import FMCSQ
X, y = make_classification(n_samples=1000, n_classes=2, random_state=0)
ensemble = FMCSQ(
  classifiers=[RandomForestClassifier(), HistGradientBoostingClassifier(), LogisticRegression()],
  quantifier=ACC(LogisticRegression(max_iter=1000)),
  fusion="median", random_state=0,
)
ensemble.fit(X, y)
X_test, y_test = make_classification(n_samples=200, n_classes=2, random_state=7)
prevalences = ensemble.predict(X_test)
print(prevalences)
import numpy as np
_, counts = np.unique(y_test, return_counts=True)
counts / y_test.shape[0]

[0.34007274 0.65992726]


array([0.5, 0.5])

In [3]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from quack.quantifiers import ACC
from quack.ensembles import FMCSQ
X, y = make_classification(n_samples=1200, n_classes=2, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
ensemble = FMCSQ(
    classifiers=[RandomForestClassifier(), HistGradientBoostingClassifier(), LogisticRegression()],
    quantifier=ACC(cv=5), fusion="cos", random_state=0,
)
ensemble.fit(X_train, y_train)
prevalences = ensemble.predict(X_test)

In [4]:
print(prevalences)
import numpy as np
_, counts = np.unique(y_test, return_counts=True)
counts / y_test.shape[0]

[0.59587697 0.40412303]


array([0.55833333, 0.44166667])